description = "An adaptation of the Beautiful Jekyll theme"
features = [
  "blog",
  "company",
  "portfolio",
  "projects",
  "minimal",
  "responsive",
  "seo",
  "google analytics",
  "bootstrap",
  "disqus",
  "light",
  "syntax highlighting",
  "multilingual",
  "portfolio",
  "projects",
  "mobile",
  "technical",
]
license = "MIT"
licenselink = "https://github.com/Artivain/artibot/blob/main/themes/artibot/LICENSE"
min_version = 0.48
name = "Artibot"
tags = [
  "blog",
  "company",
  "portfolio",
  "projects",
  "minimal",
  "responsive",
  "seo",
  "google analytics",
  "bootstrap",
  "disqus",
  "light",
  "syntax highlighting",
  "multilingual",
  "portfolio",
  "projects",
  "mobile",
  "technical",
]

[author]
homepage = "http://halogenica.net"
name = "halogenica"

# If Porting existing theme
[original]
author = "dattali"
homepage = "http://deanattali.com/beautiful-jekyll/"
repo = "https://github.com/daattali/beautiful-jekyll"
